const ORDER_STATUS = {
    PENDING: 0,
    COMPLETED: 1,
    CONFIRMED: 2,
    PICKED: 3,
    CHECKED: 4,
    PACKED: 5,
    OUTBOUNDED: 6,
    OUT_FOR_DELIVERY: 7,
    DISPUTE: 8,
    SHIPPED: 9,
    CANCELLED: 10,
    IN_PICK_LIST: 11,
    CHECKIN_OUTBOUND: 12,
    MANIFESTED_ORDER: 13,
}

export {
    ORDER_STATUS,
}
